package com.futurebytedance.mybatis.mapper;

import com.futurebytedance.mybatis.pojo.Dept;

import java.util.List;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Thu Sep 15 19:18:12 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Thu Sep 15 19:18:12 GMT+08:00 2022
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Thu Sep 15 19:18:12 GMT+08:00 2022
     */
    Dept selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Thu Sep 15 19:18:12 GMT+08:00 2022
     */
    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbggenerated Thu Sep 15 19:18:12 GMT+08:00 2022
     */
    int updateByPrimaryKey(Dept record);
}